#!/usr/bin/env bash
COMPOSITOR=$1
PROFILE=$2
DOTFILES_DIR="$HOME/.dotfiles"

cd "$DOTFILES_DIR/profiles/" || exit
for dir in *; do
	cd "$dir" || exit
	stow -D -t ~ * 2>/dev/null
	cd "../" || exit
done

if [[ "$(ls -A $DOTFILES_DIR/shared)" ]]; then
	cd "$DOTFILES_DIR/shared/" || exit
	stow --no-folding -t ~ *
fi

if [[ x"$PROFILE" != "x" ]]; then
	cd "$DOTFILES_DIR/profiles/$PROFILE" || exit
	stow --override=".*" -t ~ *
fi

cd "$HOME" || exit
exec "$COMPOSITOR"
