cursor #dee3e6
cursor_text_color #bfc8cb

foreground            #dee3e6
background            #0f1416
selection_foreground  #1d343a
selection_background  #b2cbd3
url_color             #85d2e8

color0   #0f1416
color1   #ff72a1
color2   #74e880
color3   #fff572
color4   #6bc3dc
color5   #17586b
color6   #85d2e8
color7   #e4f0f3
color8   #8b9496
color9   #ff9fbf
color10  #a5ffaf
color11  #fff9a5
color12  #a2eaff
color13  #b2eeff
color14  #cef4ff
color15  #f8fdff
