cursor #efe0d6
cursor_text_color #d6c3b6

foreground            #efe0d6
background            #19120c
selection_foreground  #412c1a
selection_background  #e3c0a6
url_color             #ffb77c

color0   #19120c
color1   #ff766e
color2   #92ff7c
color3   #ffe56e
color4   #f2a05c
color5   #763806
color6   #ffb77c
color7   #fff6ef
color8   #a59e98
color9   #ffa29c
color10  #b3ffa3
color11  #ffeea3
color12  #ffc18f
color13  #ffcca3
color14  #ffdec4
color15  #fffbf8
