cursor #f1dfd9
cursor_text_color #d8c2bb

foreground            #f1dfd9
background            #1a110f
selection_foreground  #442a21
selection_background  #e7bdb0
url_color             #ffb59c

color0   #1a110f
color1   #ff7672
color2   #98ff7f
color3   #ffe572
color4   #f29d81
color5   #7d3e28
color6   #ffb59c
color7   #fff3ef
color8   #47413e
color9   #ffa29f
color10  #b6ffa5
color11  #ffeea5
color12  #ffc0aa
color13  #ffcbb9
color14  #ffddd2
color15  #fffaf8
