icons_format = "{icon}"

[theme]
theme = "plain"

[theme.overrides]
idle_bg      = "#080a09"
idle_fg      = "#ffffff"
info_bg      = "#285577"
info_fg      = "#ffffff"
good_bg      = "#080a09"
good_fg      = "#00ff00"
warning_bg   = "#222222"
warning_fg   = "#ffa500"
critical_bg  = "#900000"
critical_fg  = "#ffffff"
separator    = "|"
separator_bg = "#080a09"
separator_fg = "#666666"


[icons]
icons = "none"

[[block]]
block = "net"
device = "^w|e"
format = " $speed_down.eng(w:3,u:B)↓ $speed_up.eng(w:3,u:B)↑ "
interval = 2

[[block]]
block = "cpu"
interval = 2
format = " cpu $utilization "

[[block]]
block = "memory"
format = " mem $mem_used.eng(w:3,u:B)/$mem_total.eng(w:3,u:B) ($mem_used_percents) "
interval = 2

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 30
format = " root $available "

[[block]]
block = "sound"
format = " vol $volume "
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %b %d  %H:%M') "
