#BORDER
# class                 border  backgr. text    indicator child_border
#client.focused         #04d3f7 #04d3f7 #110e24 #d874da   #d874da
#client.focused          #04d3f7 #04d3f7 #110e24 #04d9ff   #04d9ff
client.focused		#04d3f7 #04d3f7 #110e24 #5caab8   #5caab8
client.focused_inactive #110e24 #110e24 #ffffff #110e24   #110e24
client.unfocused        #110e24 #110e24 #04d3f7 #110e24   #222222
client.urgent           #2f343a #900000 #ffffff #900000   #900000
client.placeholder      #000000 #0c0c0c #ffffff #000000   #0c0c0c

client.background       #ffffff

#default_border pixel 1

for_window [all] border pixel 1

smart_borders on
