bar {
  status_command i3blocks -c ~/.config/sway/bar/i3blocks.conf

  font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
  font pango:Victor Mono 11

  position top
  height 22
  gaps 0px 0px 0px 0px 

  #hidden_state show 
  #mode dock
  #pango_markup enabled

  colors {
    background #120e0d
    statusline #e0b084
    separator  #8a4b38

    # class                 border  bground text
    focused_workspace       #de8f4c #de8f4c #120e0d
    active_workspace        #5c3a21 #5c3a21 #e0b084
    inactive_workspace      #120e0d #120e0d #8a6b5e
    urgent_workspace        #a03228 #a03228 #faebd7
    binding_mode            #a03228 #a03228 #faebd7
  }
}
