bar {
    status_command i3status-rs

    font pango:Victor Mono 10, Font Awesome 6 Free 10

    position top
    height 22
    gaps 0px

    colors {
        background #120e0d
        statusline #c8a27d
        separator  #3d261c

        # class                 border  bground text
        focused_workspace       #382419 #382419 #e0b084
        active_workspace        #221713 #221713 #9e7a5c
        inactive_workspace      #120e0d #120e0d #604a40
        urgent_workspace        #70221a #70221a #e0b084
        binding_mode            #70221a #70221a #e0b084
    }
}
