[General]
DisplayServer=wayland

[Wayland]
CompositorCommand=weston --shell=fullscreen-shell.so

[Theme]
ThemeDir=/etc/sddm.conf.d/themes
Current=/etc/sddm.conf.d/themes/pixelcyber
EnableAvatars=false
