# BORDER
# class                 border  backgr. text    indicator child_border
client.focused          #5D3B1F #5D3B1F #120e0d #5D3B1F   #5D3B1F
client.focused_inactive #5c3a21 #5c3a21 #e0b084 #5c3a21   #5c3a21
client.unfocused        #120e0d #120e0d #8a6b5e #120e0d   #120e0d
client.urgent           #a03228 #a03228 #faebd7 #a03228   #a03228
client.placeholder      #120e0d #120e0d #e0b084 #120e0d   #120e0d

client.background       #120e0d

#default_border pixel 1

for_window [all] border pixel 1

smart_borders on
