color0 #213021
color1 #fd4663
color2 #8bc18b
color3 #81b199
color4 #85adad
color5 #acd3ac
color6 #afd0bf
color7 #f2f3f2
color8 #5c705c
color9 #fd4663
color10 #8bc18b
color11 #81b199
color12 #85adad
color13 #acd3ac
color14 #afd0bf
color15 #f2f3f2

cursor                #f2f3f2
cursor_text_color     #1a231a
background            #1a231a
foreground            #f2f3f2
selection_foreground  #afb6af
selection_background  #213021
active_border_color   #8bc18b
inactive_border_color #213021
url_color             #8bc18b

active_tab_foreground   #1b221b
active_tab_background   #8bc18b
inactive_tab_foreground #afb6af
inactive_tab_background #213021
cursor_trail_color      #afb6af
