bar {
    status_command i3status-rs ~/.config/i3status-rust/config.toml

    font pango:Victor Mono 10

    position top
    height 22
    gaps 0px

    colors {
        background #080a09
        statusline #8fa189
        separator  #232d29

        # class                 border  bground text
        focused_workspace       #27342e #27342e #a9b6a3
        active_workspace        #18201d #18201d #70806d
        inactive_workspace      #080a09 #080a09 #43524b
        urgent_workspace        #8f4e4e #8f4e4e #e0cfcf
        binding_mode            #8f4e4e #8f4e4e #e0cfcf
    }
}
