bar {
    status_command i3status-rs ~/.config/i3status-rust/config.toml

    font pango:Victor Mono 10

    position top
    height 22
    gaps 0px

colors {
        background #080a09
        statusline #ffffff
        separator  #666666

        # class                 border  bground text
        focused_workspace       #4c7899 #285577 #ffffff
        active_workspace        #333333 #222222 #ffffff
        inactive_workspace      #080a09 #080a09 #888888
        urgent_workspace        #2f343a #900000 #ffffff
        binding_mode            #2f343a #900000 #ffffff
    }



}
