# swipe to workspaces 
bindgesture swipe:4:right workspace prev
bindgesture swipe:4:left workspace next

bindgesture swipe:2:left exec wtype -M alt -k Left
bindgesture swipe:2:right exec wtype -M alt -k Right

