set $mat_primary #b1c5ff
set $mat_darker #394e82
set $mat_overall #6e8edf


# BORDER
# class                 border  backgr. text    indicator child_border
client.focused          $mat_primary $mat_primary $mat_darker $mat_primary   $mat_primary
client.focused_inactive $mat_primary $mat_primary $mat_primary $mat_primary   $mat_primary
client.unfocused        $mat_darker $mat_darker $mat_primary $mat_darker   $mat_darker
client.urgent           $mat_overall $mat_overall $mat_primary $mat_overall   $mat_overall
client.placeholder      $mat_darker $mat_darker $mat_primary $mat_darker   $mat_darker

client.background       $mat_darker

#default_border pixel 1

for_window [all] border pixel 1

smart_borders on
