# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)




bar {
  status_command i3blocks -c ~/.config/sway/bar/i3blocks.conf

	font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
  font pango:Victor Mono 11

  position top
	height 22
	gaps 0px 0px 0px 0px 
	

	#hidden_state show 
	#mode dock
	#pango_markup enabled

  colors {
    #background #00000000
		background #161616
    statusline #04d3f7
    separator  #be3fed

    focused_workspace  #04d9ff #bc21b0 #04d9ff
    #focused_workspace  #04d3f7 #ff30e7 #04d9ff
    active_workspace   #04d9ff #bc21b0 #04d9ff
    inactive_workspace #bc21b0 #04d9ff #bc21b0
    urgent_workspace   #04d9ff #cf498d #04d9ff
    binding_mode       #04d9ff #cf498d #04d9ff

  }
}
