# i3blocks configuration file
#
# The i3blocks man page describes the usage of the binary,
# and its website describes the configuration:
#
#     https://vivien.github.io/i3blocks


# Global properties
separator=true
separator_block_width=15

[memory]
command=$HOME/.config/scripts/i3blocks/memory
label=MEM 
interval=30

[cpu_usage]
command=$HOME/.config/scripts/i3blocks/cpu_usage
interval=10
LABEL=CPU 

[battery2]
command=$HOME/.config/scripts/i3blocks/battery2
label=BAT 
markup=pango
interval=30

[volume-pipewire]
command=$HOME/.config/scripts/i3blocks/volume-pipewire
interval=once
signal=1

[date]
command=date '+%Y-%m-%d'
interval=once

[time]
command=date '+%I:%M %p'
interval=1

