#unbind C-b
set -s default-terminal 'tmux-256color'
set -g status-style 'bg=#16161e'
set -g base-index 1
unbind C-b
set -g prefix C-s
bind C-s send-prefix
#za -s prefix  
bind-key -T prefix C-h previous-window
bind-key -T prefix C-l next-window

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

